### ISSUE TITLE
Installation Stuck at node-gyp rebuild

### ISSUE THREAD

**Issue by joshglenn** [ddopson/underscore-cli#42]
On Mac OSX Mavericks. Installation hangs at node-gyp rebuild. Any idea why?

```
npm install -g underscore-cli
\
> msgpack@1.0.2 install /Users/josh/.npm-packages/lib/node_modules/underscore-cli/node_modules/msgpack
> node-gyp rebuild
```

**Comment by joshglenn** [comment]
Well, actually, it wasn't stuck. I let it run a while. This is the error I got:

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v4.1.2.tar.gz local checksum cc48ad0a64f92ef64baa00920375b15d7cd099cf1caa2d167c904d1f070194e7 not match remote febec3703a3fea9b64c46100a7b6a4408250027aa8259a2a815fd2275d502c49
gyp ERR! stack     at deref (/Users/josh/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/Users/josh/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:893:12)
gyp ERR! stack     at doNTCallback2 (node.js:430:9)
gyp ERR! stack     at process._tickCallback (node.js:344:17)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/Cellar/node/0.12.0/bin/node" "/Users/josh/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/josh/.npm-packages/lib/node_modules/underscore-cli/node_modules/msgpack
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing msgpack@1.0.2
/Users/josh/.npm-packages/bin/underscore -> /Users/josh/.npm-packages/lib/node_modules/underscore-cli/bin/underscore
underscore-cli@0.2.18 /Users/josh/.npm-packages/lib/node_modules/underscore-cli
├── underscore@1.8.3
├── coffee-script@1.10.0
├── underscore.string@3.2.2
├── JSONSelect@0.4.0
└── commander@1.0.5 (keypress@0.1.0)
```

Any ideas?

**Comment by joshglenn** [comment]
As it turns out, although there was such a plethora of installation errors, underscore seems to work just fine.
