### ISSUE TITLE
echo '{ "abc": 1 }' | underscore extract abc - fails

### ISSUE THREAD

**Issue by bedge** [ddopson/underscore-cli#47]
Ubuntu 14.04 nodejs install using: https://github.com/nodesource/distributions on fresh VM installation.

Clean up default version & cruft, then install from nodesource:
```
root@sparky:~# apt-get --purge remove nodejs npm
root@sparky:~# rm -rf /root/.node-gyp/
root@sparky:~# rm -rf /usr/lib/node_modules
root@sparky:~# curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
root@sparky:~# apt-get install nodejs
```
Above output truncated for clarity.
All output shown from commands below.
```
root@sparky:~# npm install -g underscore-cli
/usr/bin/underscore -> /usr/lib/node_modules/underscore-cli/bin/underscore

> msgpack@1.0.2 install /usr/lib/node_modules/underscore-cli/node_modules/msgpack
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.4.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/underscore-cli/node_modules/msgpack/.node-gyp"
make: Entering directory `/usr/lib/node_modules/underscore-cli/node_modules/msgpack/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
  SOLINK_MODULE(target) Release/obj.target/msgpackBinding.node
  COPY Release/msgpackBinding.node
make: Leaving directory `/usr/lib/node_modules/underscore-cli/node_modules/msgpack/build'
/usr/lib
└─┬ underscore-cli@0.2.18
  ├── coffee-script@1.10.0
  ├─┬ commander@1.0.5
  │ └── keypress@0.1.0
  ├── JSONSelect@0.4.0
  ├─┬ msgpack@1.0.2
  │ └── nan@2.2.0
  ├── underscore@1.8.3
  └── underscore.string@3.2.3

root@sparky:~# npm list
/root
└─┬ underscore-cli@0.2.18
  ├── coffee-script@1.10.0
  ├─┬ commander@1.0.5
  │ └── keypress@0.1.0
  ├── JSONSelect@0.4.0
  ├─┬ msgpack@1.0.2
  │ └── nan@2.2.0
  ├── underscore@1.8.3
  └── underscore.string@3.2.3

root@sparky:~# echo '{ "abc": 1 }' | underscore extract abc
Error while processing data: Error: data does not contain field 'a'
    at /usr/lib/node_modules/underscore-cli/bin/underscore:385:17
    at String.replace (native)
    at Function.module.exports (/usr/lib/node_modules/underscore-cli/node_modules/underscore.string/map.js:8:14)
    at Object.commands.extract.fn (/usr/lib/node_modules/underscore-cli/bin/underscore:380:9)
    at /usr/lib/node_modules/underscore-cli/bin/underscore:758:21
    at /usr/lib/node_modules/underscore-cli/bin/underscore:885:20
    at Socket.<anonymous> (/usr/lib/node_modules/underscore-cli/bin/underscore:960:7)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
```
However, this does work:
```
root@sparky:~# echo '{ "a": 1 }' | underscore extract a
1
```

**Comment by bedge** [comment]
Same results installing non-globally as non-root user.

```
19:48 $ npm list
/home/bedge
└── (empty)

19:48 $ npm install underscore-cli

> msgpack@1.0.2 install /home/bedge/node_modules/msgpack
> node-gyp rebuild

make: Entering directory `/home/bedge/node_modules/msgpack/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
  SOLINK_MODULE(target) Release/obj.target/msgpackBinding.node
  COPY Release/msgpackBinding.node
make: Leaving directory `/home/bedge/node_modules/msgpack/build'
/home/bedge
└─┬ underscore-cli@0.2.18
  ├── coffee-script@1.10.0
  ├─┬ commander@1.0.5
  │ └── keypress@0.1.0
  ├── JSONSelect@0.4.0
  ├─┬ msgpack@1.0.2
  │ └── nan@2.2.0
  ├── underscore@1.8.3
  └── underscore.string@3.2.3

npm WARN ENOENT ENOENT: no such file or directory, open '/home/bedge/package.json'
npm WARN EPACKAGEJSON bedge No description
npm WARN EPACKAGEJSON bedge No repository field.
npm WARN EPACKAGEJSON bedge No README data
npm WARN EPACKAGEJSON bedge No license field.

19:48 $ echo '{ "abc": 1 }' | underscore extract abc
Error while processing data: Error: data does not contain field 'a'
    at /usr/lib/node_modules/underscore-cli/bin/underscore:385:17
    at String.replace (native)
    at Function.module.exports (/usr/lib/node_modules/underscore-cli/node_modules/underscore.string/map.js:8:14)
    at Object.commands.extract.fn (/usr/lib/node_modules/underscore-cli/bin/underscore:380:9)
    at /usr/lib/node_modules/underscore-cli/bin/underscore:758:21
    at /usr/lib/node_modules/underscore-cli/bin/underscore:885:20
    at Socket.<anonymous> (/usr/lib/node_modules/underscore-cli/bin/underscore:960:7)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
```

**Comment by bedge** [comment]
Found a workaround by locking down these versions:
```
		keypress@0.1.0 \
		commander@1.0.5 \
		JSONSelect@0.4.0 \
		nan@1.8.4 \
		underscore@1.8.3 \
		underscore.string@3.1.1 \
		underscore-cli@0.2.18 \
		coffee-script@1.9.3
```
Not ideal as any npm update will possibly break it again. But hopefully this is enough of a hint to isolate.

**Comment by gregorskii** [comment]
This is an issue for me as well.

+1

**Comment by zayass** [comment]
@bedge only this is important
```
 underscore.string@3.1.1 \
```

**Comment by bedge** [comment]
What's the new release ETA, or, can one get npm to install a development version?

**Comment by ddopson** [comment]
Are you saying that there's a bug fix in github that's not been pushed to
npm?

I can look into pushing a version.

I believe you can also specify a git url as the version in npm.

**Comment by bedge** [comment]
Exactly. I still get 2.1.18 using `npm install -g underscore-cli`
I tried specifying a commit sha1 and URL of the commit, but it responds with:
```
npm ERR! No compatible version found: underscore-cli@3c180f46d0b430b92b3ee6bdc614f024dc902a1d
npm ERR! Valid install targets:
npm ERR! 0.2.18, 0.2.17, 0.2.16, 0.2.15, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.1.0
npm ERR!
```

So, yes, if you could push a new version I think that would do it.

thanks.

**Comment by zayass** [comment]
use this for install from github master 
```
npm install -g ddopson/underscore-cli                         
```

```
/usr/local/bin/underscore -> /usr/local/lib/node_modules/underscore-cli/bin/underscore
/usr/local/lib
└── underscore-cli@0.2.18  (git://github.com/ddopson/underscore-cli.git#3c180f46d0b430b92b3ee6bdc614f024dc902a1d)
```

**Comment by arcanis** [comment]
This issue is still there.

**Comment by bedge** [comment]
We dropped underscore as a viable tool set component and opted for jq as it's a static binary that's virtually impossible to break because of dependency issues.
The syntax does need to change though.
