### ISSUE TITLE
Syntax Error When Attempting to Run 'underscore'

### ISSUE THREAD

**Issue by Stunner** [ddopson/underscore-cli#51]
Installed this script following instructions from the README and am seeing the following error:

```
$ underscore
/usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:69
        .join(' ');
         ^
TypeError: undefined is not a function
    at /usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:69:10
    at Array.map (native)
    at Command.commandHelp (/usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:62:6)
    at Command.helpInformation (/usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:193:26)
    at printHelp (/usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:246:25)
    at main (/usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:792:5)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.30.1/versions/io.js/v1.2.0/lib/node_modules/underscore-cli/bin/underscore:1024:3)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
```

**Comment by tugberkugurlu** [comment]
same here:

```
underscore help                                       
Unknown command: 'help'
/usr/lib/node_modules/underscore-cli/bin/underscore:69
        .join(' ');
         ^

TypeError: _(...).map(...).join is not a function
    at /usr/lib/node_modules/underscore-cli/bin/underscore:69:10
    at Array.map (native)
    at Command.commandHelp (/usr/lib/node_modules/underscore-cli/bin/underscore:62:6)
    at Command.helpInformation (/usr/lib/node_modules/underscore-cli/bin/underscore:193:26)
    at printHelp (/usr/lib/node_modules/underscore-cli/bin/underscore:243:27)
    at Command.<anonymous> (/usr/lib/node_modules/underscore-cli/bin/underscore:802:7)
    at emitOne (events.js:77:13)
    at Command.emit (events.js:169:7)
    at Command.parseArgs (/usr/lib/node_modules/underscore-cli/node_modules/commander/lib/commander.js:408:12)
    at Command.parse (/usr/lib/node_modules/underscore-cli/node_modules/commander/lib/commander.js:352:15)

```

**Comment by jinleileiking** [comment]
➜  ~ git:(master) ✗ underscore
/home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:69
        .join(' ');
         ^
TypeError: undefined is not a function
    at /home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:69:10
    at Array.map (native)
    at Command.commandHelp (/home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:62:6)
    at Command.helpInformation (/home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:191:26)
    at printHelp (/home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:244:25)
    at main (/home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:790:5)
    at Object.<anonymous> (/home/lk/.jumbo/lib/node_modules/underscore-cli/bin/underscore:1022:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by wfelbermeier** [comment]
same here

**Comment by sn0w** [comment]
same here

**Comment by maqic** [comment]
same

**Comment by jinleileiking** [comment]
use `pjson` instead.

**Comment by carljokl** [comment]
Same error. Given the thread it doesn't look like there is a work around.

**Comment by sn0w** [comment]
Another good tool is `jq`

Just switched to it

**Comment by csabahenk** [comment]
Does any of these alternatives support the kind of smart pretty printing underscore-cli had?

I mean, dumb is like this:

```
$ echo '[[[["This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long text" ]]]]' |  python -mjson.tool
[
    [
        [
            [
                "This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long text"
            ]
        ]
    ]
]
$ echo '[[[[1]]]]' | python -mjson.tool
[
    [
        [
            [
                1
            ]
        ]
    ]
]
```

Smart is like this:

```
 echo '[[[["This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long text" ]]]]' | underscore print       
[
  [
    [
      [
        "This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long text"
      ]
    ]
  ]
]
$ echo '[[[[1]]]]' | underscore print  
[[[[1]]]]
```

It's a killer feature when you have to dig through a lenghty JSON data by eye.

**Comment by csabahenk** [comment]
By the way, I have a working installation with these deps deployed:

```
/home/csaba/node/src/underscore-cli $ npm list
underscore-cli@0.2.17 /home/csaba/node/src/underscore-cli
├── coffee-script@1.6.3
├── commander@2.0.0
├── JSONSelect@0.4.0
├─┬ mocha@1.14.0
│ ├── debug@0.7.3
│ ├── diff@1.0.7
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.1
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.12
│ │   ├── lru-cache@2.3.1
│ │   └── sigmund@1.0.0
│ ├── growl@1.7.0
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ └── mkdirp@0.3.5
├── msgpack@0.2.1
├── underscore@1.5.2
└── underscore.string@2.3.3
```
 
So the fix could be to enforce these exact versions.

**Comment by rubycut** [comment]
+1

**Comment by smartifier-reilly** [comment]
I also get "TypeError: _(...).map(...).join is not a function" MacOs 10.11.12 (El Capitan)

$ underscore
/usr/local/lib/node_modules/underscore-cli/bin/underscore:69
        .join(' ');
         ^

TypeError: _(...).map(...).join is not a function
    at /usr/local/lib/node_modules/underscore-cli/bin/underscore:69:10
    at Array.map (native)
    at Command.commandHelp (/usr/local/lib/node_modules/underscore-cli/bin/underscore:62:6)
    at Command.helpInformation (/usr/local/lib/node_modules/underscore-cli/bin/underscore:193:26)
    at printHelp (/usr/local/lib/node_modules/underscore-cli/bin/underscore:246:25)
    at main (/usr/local/lib/node_modules/underscore-cli/bin/underscore:792:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/underscore-cli/bin/underscore:1024:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by brianspolarich** [comment]
+1 (10.11.4)
