### ISSUE TITLE
"help formats" doesn't work

### ISSUE THREAD

**Issue by soichih** [ddopson/underscore-cli#53]
I am trying to find what formats are available under --outfmt (without looking at the code..)

README says to "look at help formats". 

I think it means to do following, but I am getting an error message (on v0.2.18)

```
$ underscore help formats
Unknown command: 'help,formats'

/usr/lib/node_modules/underscore-cli/bin/underscore:69
        .join(' ');
         ^
TypeError: Object  has no method 'join'
    at /usr/lib/node_modules/underscore-cli/bin/underscore:69:10
    at Array.map (native)
    at Command.commandHelp (/usr/lib/node_modules/underscore-cli/bin/underscore:62:6)
    at Command.helpInformation (/usr/lib/node_modules/underscore-cli/bin/underscore:193:26)
    at printHelp (/usr/lib/node_modules/underscore-cli/bin/underscore:243:27)
    at Command.<anonymous> (/usr/lib/node_modules/underscore-cli/bin/underscore:802:7)
    at Command.emit (events.js:95:17)
    at Command.parseArgs (/usr/lib/node_modules/underscore-cli/node_modules/commander/lib/commander.js:408:12)
    at Command.parse (/usr/lib/node_modules/underscore-cli/node_modules/commander/lib/commander.js:352:15)
    at main (/usr/lib/node_modules/underscore-cli/bin/underscore:804:13)

```

**Comment by nikmauro** [comment]
```
[root@www4 ~]# underscore help
Unknown command: 'help'

/usr/lib/node_modules/underscore-cli/bin/underscore:69
        .join(' ');
         ^
TypeError: Object  has no method 'join'
    at /usr/lib/node_modules/underscore-cli/bin/underscore:69:10
    at Array.map (native)
    at Command.commandHelp (/usr/lib/node_modules/underscore-cli/bin/underscore:62:6)
    at Command.helpInformation (/usr/lib/node_modules/underscore-cli/bin/underscore:193:26)
    at printHelp (/usr/lib/node_modules/underscore-cli/bin/underscore:243:27)
    at Command.<anonymous> (/usr/lib/node_modules/underscore-cli/bin/underscore:802:7)
    at Command.EventEmitter.emit (events.js:95:17)
    at Command.parseArgs (/usr/lib/node_modules/underscore-cli/node_modules/commander/lib/commander.js:408:12)
    at Command.parse (/usr/lib/node_modules/underscore-cli/node_modules/commander/lib/commander.js:352:15)
    at main (/usr/lib/node_modules/underscore-cli/bin/underscore:804:13)
[root@www4 ~]# 

```

**Comment by soichih** [comment]
I am getting this error on "underscore select" as well.

```
# docker inspect 1963eb87dbc1 | underscore select .Status
["running"]
# docker inspect 1963eb87dbc1 | underscore select .Status --outfmt text
Error formatting output data in mode 'text': Object running has no method 'join'
```

I am using underscore-cli 0.2.18 on node v0.10.42 on RHEL7.2.1511

**Comment by AbsurdMagpieScrutinies** [comment]
Two years later, still broken

```  
$ underscore help formats
Unknown command: formats

Usage:
     underscore <command> [--in <filename>|--data <JSON>|--nodata] [--infmt <format>]
                         [--out <filename>] [--outfmt <format>] [--quiet] [--strict] [--color] [--text] 
                         [--trace] [--wrapwidth <width>] [--coffee] [--js]
 Commands:
    help [command]      Print more detailed help and examples for a specific command

```

and the output formats are broken too

```

$ underscore --in    some.json  --outfmt inspect
Usage:
     underscore <command> [--in <filename>|--data <JSON>|--nodata] [--infmt <format>]
                         [--out <filename>] [--outfmt <format>] [--quiet] [--strict] [--color] [--text] 
                         [--trace] [--wrapwidth <width>] [--coffee] [--js]
 Commands:
    help [command]      Print more detailed help and examples for a specific command
```

**Comment by cClaude** [comment]
Theses issues are about same subject : 
* #20
* #22 
* #53
